# Generated by Django 5.0.7 on 2024-07-20 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=False)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clientName', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-updatedAt'],
            },
        ),
    ]
